-- ========================================================
--  Sample data generated
--  Includes mock users and a selection of video games for database testing
--  Generated by: Gemini (Google AI)
--  Date: January 15, 2026
-- ========================================================
-- mysql database
create database L1DB;

use L1DB;


create table if not exists users (
    id int auto_increment primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    address varchar(255) not null
);

create table if not exists games (
    id int auto_increment primary key,
    name varchar(255) not null,
    publisher varchar(255) not null,
    year int not null,
    `system` varchar(255) not null,
    `condition` varchar(255) not null,
    ownerId int not null,
    foreign key(ownerid) references users(id)
);



--sample data
INSERT INTO users (name, email, password, address) VALUES
('Alice', 'alice@example.com', 'password123', '123 Main St'),
('Bob', 'bob@example.com', 'password456', '456 Elm St');


INSERT INTO games (name, publisher, year, `system`, `condition`, ownerId) VALUES
('Super Mario Bros', 'Nintendo', 1985, 'NES', 'Good', 1),
('Overwatch', 'Blizzard Entertainment', 2016, 'PlayStation 5', 'Good', 1),
('Fortnite', 'Epic Games', 2017, 'Xbox One', 'Mint', 1),
('Red Dead Redemption', 'Rockstar Games', 2010, 'PlayStation 4', 'Fair', 2);

select * from games
select * from users
